### ISSUE TITLE
Streamlink 플러그인 에러

### ISSUE THREAD

**Issue by leekcake** [leekcake/TwitchRecorder-GoogleDrive#2]
Exception in thread Thread-TwitchHLSStreamWorker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/mnt/recorder/.venv/lib/python3.8/site-packages/streamlink/stream/segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "/mnt/recorder/.venv/lib/python3.8/site-packages/streamlink/stream/hls.py", line 307, in iter_segments
    self.reload_playlist()
  File "/mnt/recorder/.venv/lib/python3.8/site-packages/streamlink/stream/hls.py", line 235, in reload_playlist
    self.process_sequences(playlist, sequences)
  File "/mnt/recorder/.venv/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 210, in process_sequences
    return super(TwitchHLSStreamWorker, self).process_sequences(playlist, sequences)
TypeError: super(type, obj): obj must be an instance or subtype of type

현재 이 에러가 사용중인 환경때문인지는 모르겠으나 발생하고 있기 때문에, 임시로 '/mnt/recorder/.venv/lib/python3.8/site-packages/streamlink/plugins/twitch.py' 파일에 있는 super 명령에서 type,obj 를 제거하는것으로 임시 해결, 플러그인 버젼을 내리는 등의 추가 액션이 필요할 수도 있음

**Comment by leekcake** [comment]
해결된 줄 알았으나, 일부 스트림에 대해 발생하는 오류로 보임, 일단 파일 첨부후 문제 재 오픈

이 프로젝트의 문제인지는 더 확인이 필요함

[twitch.zip](https://github.com/leekcake/TwitchRecorder/files/5021200/twitch.zip)

**Comment by leekcake** [comment]
약 2일이 지났지만, 큰 오류 없이 정상적으로 다운로드 되는것으로 보임. 이게 문제가 되는 코드였으면 스팀링크에 계속 남아있었을리가 없을텐데
